version: '3.8'
services:
  app:
    image: ruby:2.7-alpine
    entrypoint: ['ruby', 'solution_test.rb']
    volumes:
      - .:/app
      - ../test:/test
    working_dir: /app
    environment:
      BUNDLE_PATH: .bundle
